### ISSUE TITLE
The correct config for assembly

### ISSUE THREAD

**Issue by jessypink** [Lihis/android_kernel_lenovo_a7-50#1]
Could you tell me the correct config to build the kernel? There are many there, I can not find the right one

**Comment by Lihis** [comment]
To be honest; I don't remember anymore since it's been almost two years when I have been last time building this (and I don't have this device anymore).

I'll keep this issue open so if you find the answer feel free to comment it in here.

**Comment by Lihis** [comment]
Build with `arm-eabi-4.6` toolchain and project `lcsh82_tb_3gfull_kk` for `makeMtk`.
